[build]
command = "./build.sh"
publish = ".output/public"

[build.environment]
NODE_VERSION = "20"
YARN_VERSION = "1.22.22"

# Configuration PWA - Headers pour service worker
[[headers]]
for = "/sw.js"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/workbox-*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les icônes PWA
[[headers]]
for = "/*.png"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Headers pour le manifest
[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"
Content-Type = "application/manifest+json"
